import streamlit as st


st.title("About Me 🎲")
st.write("")
st.subheader("How did I get here?")
st.write("Following my graduation in Marketing, I immersed myself in the world of data analytics for digital marketing through an opportunity at DP6. Energized by this, I embarked on a journey of skill development, mastering data processing languages, statistical modeling, ETL, web analytics/martech tools, and AdTech platforms. My fascination and determination to make things happen propelled my growth, making me a key analyst specializing in media performance war rooms (serving Itaú, Stellantis, and Bradesco), leading to involvement in digital advertising committees at IAB Brazil (Internet Advertising Bureau) and conducting training sessions, courses, and Google Analytics classes for both markets and NGOs.")
st.write("The experience gained, connections made, and visibility of my work paved the way for me as a Business Intelligence Lead at Estadão, where I spearheaded the publisher's digital transformation. This dream role allowed me to apply my expertise from scratch, implementing comprehensive analytics across digital business modalities, establishing reporting structures and dashboards for business optimization, orchestrating multi-platform integrations for CRM and Adtech activations, and structuring a customer data platform for more precise segmentations in digital marketing and product growth initiatives. Additionally, I led a team of 8 talented individuals and provided data analytics training to journalists and business vertical teams across the publisher. With a solid foundation laid, I founded the Growth Marketing Analytics department, overseeing optimization of all digital product channels (owned & earned) and managing multidisciplinary teams for each channel, employing testing/experimentation methodologies, media attribution, and data science for business optimization.")
st.write("These roles helped me realize my talent for fostering collaboration towards common goals (in a relaxed environment), as well as contributing to the development of team members and thereby having a measurable impact on business outcomes.")
st.write("Driven by curiosity, deep involvement with data engineering and data science throughout my career led me to pursue an MBA in Big Data & Data Science, filling technical and methodological knowledge gaps in the field. This journey culminated in the honor of having my thesis selected among the top 10 across all MBA courses. With an ever-growing interest and expertise in data science, I was invited back to DP6 as a Business Analytics Manager, overseeing 21 remarkable individuals across multiple data science projects. Together, we delivered projects spanning Multichannel Attribution, Forecasting, Propensity Models, Google Analytics 4 implementation, Data Quality & Governance, and Customer Data Platform integration with Salesforce, navigating through ever-evolving landscapes and learning immensely from our experiences.")
st.write("Taking a brief pause to recharge after the pandemic and pursue personal projects, I am now revitalized and eager to take on new challenges in data analytics and data science.")
st.write("Hence, I've been contemplating documenting my thoughts on data strategy, the art of leadership in driving data teams and projects, mastering data-driven innovation, and perhaps even delving into the analysis stemming from artificial intelligence applied to marketing and digital products, and its real-world applications...")
